duti -s dev.zed.Zed .bsl all
duti -s dev.zed.Zed .os all
duti -s dev.zed.Zed .2da all
duti -s dev.zed.Zed .4dm all
duti -s dev.zed.Zed .abap all
duti -s dev.zed.Zed .asddls all
duti -s dev.zed.Zed .abnf all
duti -s dev.zed.Zed .asc all
duti -s dev.zed.Zed .ash all
duti -s dev.zed.Zed .aidl all
duti -s dev.zed.Zed .al all
duti -s dev.zed.Zed .ampl all
duti -s dev.zed.Zed .mod all
duti -s dev.zed.Zed .g4 all
duti -s dev.zed.Zed .apib all
duti -s dev.zed.Zed .apl all
duti -s dev.zed.Zed .dyalog all
duti -s dev.zed.Zed .asl all
duti -s dev.zed.Zed .dsl all
duti -s dev.zed.Zed .asn all
duti -s dev.zed.Zed .asn1 all
duti -s dev.zed.Zed .asax all
duti -s dev.zed.Zed .ascx all
duti -s dev.zed.Zed .ashx all
duti -s dev.zed.Zed .asmx all
duti -s dev.zed.Zed .aspx all
duti -s dev.zed.Zed .axd all
duti -s dev.zed.Zed .dats all
duti -s dev.zed.Zed .hats all
duti -s dev.zed.Zed .sats all
duti -s dev.zed.Zed .as all
duti -s dev.zed.Zed .adb all
duti -s dev.zed.Zed .ada all
duti -s dev.zed.Zed .ads all
duti -s dev.zed.Zed .txt all
duti -s dev.zed.Zed .afm all
duti -s dev.zed.Zed .agda all
duti -s dev.zed.Zed .als all
duti -s dev.zed.Zed .OutJob all
duti -s dev.zed.Zed .PcbDoc all
duti -s dev.zed.Zed .PrjPCB all
duti -s dev.zed.Zed .SchDoc all
duti -s dev.zed.Zed .as all
duti -s dev.zed.Zed .angelscript all
duti -s dev.zed.Zed .antlers.html all
duti -s dev.zed.Zed .antlers.php all
duti -s dev.zed.Zed .antlers.xml all
duti -s dev.zed.Zed .apacheconf all
duti -s dev.zed.Zed .vhost all
duti -s dev.zed.Zed .htaccess all
duti -s dev.zed.Zed .cls all
duti -s dev.zed.Zed .trigger all
duti -s dev.zed.Zed .agc all
duti -s dev.zed.Zed .applescript all
duti -s dev.zed.Zed .scpt all
duti -s dev.zed.Zed .arc all
duti -s dev.zed.Zed .asciidoc all
duti -s dev.zed.Zed .adoc all
duti -s dev.zed.Zed .asc all
duti -s dev.zed.Zed .aj all
duti -s dev.zed.Zed .asm all
duti -s dev.zed.Zed .a51 all
duti -s dev.zed.Zed .i all
duti -s dev.zed.Zed .inc all
duti -s dev.zed.Zed .nas all
duti -s dev.zed.Zed .nasm all
duti -s dev.zed.Zed .astro all
duti -s dev.zed.Zed .asy all
duti -s dev.zed.Zed .aug all
duti -s dev.zed.Zed .ahk all
duti -s dev.zed.Zed .ahkl all
duti -s dev.zed.Zed .au3 all
duti -s dev.zed.Zed .avdl all
duti -s dev.zed.Zed .awk all
duti -s dev.zed.Zed .auk all
duti -s dev.zed.Zed .gawk all
duti -s dev.zed.Zed .mawk all
duti -s dev.zed.Zed .nawk all
duti -s dev.zed.Zed .bas all
duti -s dev.zed.Zed .bal all
duti -s dev.zed.Zed .bat all
duti -s dev.zed.Zed .cmd all
duti -s dev.zed.Zed .bf all
duti -s dev.zed.Zed .befunge all
duti -s dev.zed.Zed .bf all
duti -s dev.zed.Zed .be all
duti -s dev.zed.Zed .bib all
duti -s dev.zed.Zed .bibtex all
duti -s dev.zed.Zed .bicep all
duti -s dev.zed.Zed .bs all
duti -s dev.zed.Zed .bison all
duti -s dev.zed.Zed .bb all
duti -s dev.zed.Zed .blade all
duti -s dev.zed.Zed .blade.php all
duti -s dev.zed.Zed .bb all
duti -s dev.zed.Zed .decls all
duti -s dev.zed.Zed .bmx all
duti -s dev.zed.Zed .bsv all
duti -s dev.zed.Zed .bs all
duti -s dev.zed.Zed .boo all
duti -s dev.zed.Zed .bpl all
duti -s dev.zed.Zed .b all
duti -s dev.zed.Zed .bf all
duti -s dev.zed.Zed .bs all
duti -s dev.zed.Zed .brs all
duti -s dev.zed.Zed .browserslistrc all
duti -s dev.zed.Zed .c all
duti -s dev.zed.Zed .cats all
duti -s dev.zed.Zed .h all
duti -s dev.zed.Zed .idc all
duti -s dev.zed.Zed .cs all
duti -s dev.zed.Zed .cake all
duti -s dev.zed.Zed .csx all
duti -s dev.zed.Zed .linq all
duti -s dev.zed.Zed .cpp all
duti -s dev.zed.Zed .c++ all
duti -s dev.zed.Zed .cc all
duti -s dev.zed.Zed .cp all
duti -s dev.zed.Zed .cppm all
duti -s dev.zed.Zed .cxx all
duti -s dev.zed.Zed .h all
duti -s dev.zed.Zed .h++ all
duti -s dev.zed.Zed .hh all
duti -s dev.zed.Zed .hpp all
duti -s dev.zed.Zed .hxx all
duti -s dev.zed.Zed .inc all
duti -s dev.zed.Zed .inl all
duti -s dev.zed.Zed .ino all
duti -s dev.zed.Zed .ipp all
duti -s dev.zed.Zed .ixx all
duti -s dev.zed.Zed .re all
duti -s dev.zed.Zed .tcc all
duti -s dev.zed.Zed .tpp all
duti -s dev.zed.Zed .txx all
duti -s dev.zed.Zed .c-objdump all
duti -s dev.zed.Zed .chs all
duti -s dev.zed.Zed .cds all
duti -s dev.zed.Zed .cil all
duti -s dev.zed.Zed .clp all
duti -s dev.zed.Zed .cmake all
duti -s dev.zed.Zed .cmake.in all
duti -s dev.zed.Zed .cob all
duti -s dev.zed.Zed .cbl all
duti -s dev.zed.Zed .ccp all
duti -s dev.zed.Zed .cobol all
duti -s dev.zed.Zed .cpy all
duti -s dev.zed.Zed .dae all
duti -s dev.zed.Zed .cson all
duti -s dev.zed.Zed .css all
# duti -s dev.zed.Zed .csv all
duti -s Numbers .csv all

duti -s dev.zed.Zed .cue all
duti -s dev.zed.Zed .w all
duti -s dev.zed.Zed .cabal all
duti -s dev.zed.Zed .cdc all
duti -s dev.zed.Zed .cairo all
duti -s dev.zed.Zed .mligo all
duti -s dev.zed.Zed .capnp all
duti -s dev.zed.Zed .mss all
duti -s dev.zed.Zed .ceylon all
duti -s dev.zed.Zed .chpl all
duti -s dev.zed.Zed .ch all
duti -s dev.zed.Zed .crc32 all
duti -s dev.zed.Zed .md2 all
duti -s dev.zed.Zed .md4 all
duti -s dev.zed.Zed .md5 all
duti -s dev.zed.Zed .sha1 all
duti -s dev.zed.Zed .sha2 all
duti -s dev.zed.Zed .sha224 all
duti -s dev.zed.Zed .sha256 all
duti -s dev.zed.Zed .sha256sum all
duti -s dev.zed.Zed .sha3 all
duti -s dev.zed.Zed .sha384 all
duti -s dev.zed.Zed .sha512 all
duti -s dev.zed.Zed .ck all
duti -s dev.zed.Zed .circom all
duti -s dev.zed.Zed .cirru all
duti -s dev.zed.Zed .clw all
duti -s dev.zed.Zed .clar all
duti -s dev.zed.Zed .asp all
duti -s dev.zed.Zed .icl all
duti -s dev.zed.Zed .dcl all
duti -s dev.zed.Zed .click all
duti -s dev.zed.Zed .clj all
duti -s dev.zed.Zed .bb all
duti -s dev.zed.Zed .boot all
duti -s dev.zed.Zed .cl2 all
duti -s dev.zed.Zed .cljc all
duti -s dev.zed.Zed .cljs all
duti -s dev.zed.Zed .cljs.hl all
duti -s dev.zed.Zed .cljscm all
duti -s dev.zed.Zed .cljx all
duti -s dev.zed.Zed .hic all
duti -s dev.zed.Zed .soy all
duti -s dev.zed.Zed .conllu all
duti -s dev.zed.Zed .conll all
duti -s dev.zed.Zed .ql all
duti -s dev.zed.Zed .qll all
duti -s dev.zed.Zed .coffee all
duti -s dev.zed.Zed ._coffee all
duti -s dev.zed.Zed .cake all
duti -s dev.zed.Zed .cjsx all
duti -s dev.zed.Zed .iced all
duti -s dev.zed.Zed .cfm all
duti -s dev.zed.Zed .cfml all
duti -s dev.zed.Zed .cfc all
duti -s dev.zed.Zed .lisp all
duti -s dev.zed.Zed .asd all
duti -s dev.zed.Zed .cl all
duti -s dev.zed.Zed .l all
duti -s dev.zed.Zed .lsp all
duti -s dev.zed.Zed .ny all
duti -s dev.zed.Zed .podsl all
duti -s dev.zed.Zed .sexp all
duti -s dev.zed.Zed .cwl all
duti -s dev.zed.Zed .cp all
duti -s dev.zed.Zed .cps all
duti -s dev.zed.Zed .cl all
duti -s dev.zed.Zed .coq all
duti -s dev.zed.Zed .v all
duti -s dev.zed.Zed .cppobjdump all
duti -s dev.zed.Zed .c++-objdump all
duti -s dev.zed.Zed .c++objdump all
duti -s dev.zed.Zed .cpp-objdump all
duti -s dev.zed.Zed .cxx-objdump all
duti -s dev.zed.Zed .creole all
duti -s dev.zed.Zed .cr all
duti -s dev.zed.Zed .orc all
duti -s dev.zed.Zed .udo all
duti -s dev.zed.Zed .csd all
duti -s dev.zed.Zed .sco all
duti -s dev.zed.Zed .cu all
duti -s dev.zed.Zed .cuh all
duti -s dev.zed.Zed .cue all
duti -s dev.zed.Zed .curry all
duti -s dev.zed.Zed .cy all
duti -s dev.zed.Zed .cyp all
duti -s dev.zed.Zed .cypher all
duti -s dev.zed.Zed .pyx all
duti -s dev.zed.Zed .pxd all
duti -s dev.zed.Zed .pxi all
duti -s dev.zed.Zed .d all
duti -s dev.zed.Zed .di all
duti -s dev.zed.Zed .d-objdump all
duti -s dev.zed.Zed .d2 all
duti -s dev.zed.Zed .com all
duti -s dev.zed.Zed .dm all
duti -s dev.zed.Zed .zone all
duti -s dev.zed.Zed .arpa all
duti -s dev.zed.Zed .d all
duti -s dev.zed.Zed .dfy all
duti -s dev.zed.Zed .darcspatch all
duti -s dev.zed.Zed .dpatch all
duti -s dev.zed.Zed .dart all
duti -s dev.zed.Zed .dwl all
duti -s dev.zed.Zed .dsc all
duti -s dev.zed.Zed .dsc all
duti -s dev.zed.Zed .dhall all
duti -s dev.zed.Zed .diff all
duti -s dev.zed.Zed .patch all
duti -s dev.zed.Zed .x all
duti -s dev.zed.Zed .dockerfile all
duti -s dev.zed.Zed .djs all
duti -s dev.zed.Zed .env all
duti -s dev.zed.Zed .env all
duti -s dev.zed.Zed .env.ci all
duti -s dev.zed.Zed .env.dev all
duti -s dev.zed.Zed .env.development all
duti -s dev.zed.Zed .env.development.local all
duti -s dev.zed.Zed .env.example all
duti -s dev.zed.Zed .env.local all
duti -s dev.zed.Zed .env.prod all
duti -s dev.zed.Zed .env.production all
duti -s dev.zed.Zed .env.staging all
duti -s dev.zed.Zed .env.test all
duti -s dev.zed.Zed .env.testing all
duti -s dev.zed.Zed .dylan all
duti -s dev.zed.Zed .dyl all
duti -s dev.zed.Zed .intr all
duti -s dev.zed.Zed .lid all
duti -s dev.zed.Zed .e all
duti -s dev.zed.Zed .eml all
duti -s dev.zed.Zed .mbox all
duti -s dev.zed.Zed .ebnf all
duti -s dev.zed.Zed .ecl all
duti -s dev.zed.Zed .eclxml all
duti -s dev.zed.Zed .ecl all
duti -s dev.zed.Zed .ejs all
duti -s dev.zed.Zed .ect all
duti -s dev.zed.Zed .ejs.t all
duti -s dev.zed.Zed .jst all
duti -s dev.zed.Zed .eq all
duti -s dev.zed.Zed .sch all
duti -s dev.zed.Zed .brd all
duti -s dev.zed.Zed .eb all
duti -s dev.zed.Zed .epj all
duti -s dev.zed.Zed .html all
duti -s dev.zed.Zed .edgeql all
duti -s dev.zed.Zed .esdl all
duti -s dev.zed.Zed .editorconfig all
duti -s dev.zed.Zed .editorconfig all
duti -s dev.zed.Zed .edc all
duti -s dev.zed.Zed .e all
duti -s dev.zed.Zed .ex all
duti -s dev.zed.Zed .exs all
duti -s dev.zed.Zed .elm all
duti -s dev.zed.Zed .elv all
duti -s dev.zed.Zed .abbrev_defs all
duti -s dev.zed.Zed .emacs all
duti -s dev.zed.Zed .emacs.desktop all
duti -s dev.zed.Zed .gnus all
duti -s dev.zed.Zed .spacemacs all
duti -s dev.zed.Zed .viper all
duti -s dev.zed.Zed .el all
duti -s dev.zed.Zed .emacs all
duti -s dev.zed.Zed .emacs.desktop all
duti -s dev.zed.Zed .em all
duti -s dev.zed.Zed .emberscript all
duti -s dev.zed.Zed .erl all
duti -s dev.zed.Zed .app all
duti -s dev.zed.Zed .app.src all
duti -s dev.zed.Zed .es all
duti -s dev.zed.Zed .escript all
duti -s dev.zed.Zed .hrl all
duti -s dev.zed.Zed .xrl all
duti -s dev.zed.Zed .yrl all
duti -s dev.zed.Zed .e all
duti -s dev.zed.Zed .ex all
duti -s dev.zed.Zed .fs all
duti -s dev.zed.Zed .fsi all
duti -s dev.zed.Zed .fsx all
duti -s dev.zed.Zed .fst all
duti -s dev.zed.Zed .fsti all
duti -s dev.zed.Zed .flf all
duti -s dev.zed.Zed .fx all
duti -s dev.zed.Zed .flux all
duti -s dev.zed.Zed .factor all
duti -s dev.zed.Zed .factor-boot-rc all
duti -s dev.zed.Zed .factor-rc all
duti -s dev.zed.Zed .fy all
duti -s dev.zed.Zed .fancypack all
duti -s dev.zed.Zed .fan all
duti -s dev.zed.Zed .dsp all
duti -s dev.zed.Zed .fnl all
duti -s dev.zed.Zed .f all
duti -s dev.zed.Zed .fs all
duti -s dev.zed.Zed .ftl all
duti -s dev.zed.Zed .for all
duti -s dev.zed.Zed .eam.fs all
duti -s dev.zed.Zed .fth all
duti -s dev.zed.Zed .4th all
duti -s dev.zed.Zed .f all
duti -s dev.zed.Zed .for all
duti -s dev.zed.Zed .forth all
duti -s dev.zed.Zed .fr all
duti -s dev.zed.Zed .frt all
duti -s dev.zed.Zed .fs all
duti -s dev.zed.Zed .f all
duti -s dev.zed.Zed .f77 all
duti -s dev.zed.Zed .for all
duti -s dev.zed.Zed .fpp all
duti -s dev.zed.Zed .f90 all
duti -s dev.zed.Zed .f03 all
duti -s dev.zed.Zed .f08 all
duti -s dev.zed.Zed .f95 all
duti -s dev.zed.Zed .bi all
duti -s dev.zed.Zed .bas all
duti -s dev.zed.Zed .ftl all
duti -s dev.zed.Zed .fr all
duti -s dev.zed.Zed .fut all
duti -s dev.zed.Zed .g all
duti -s dev.zed.Zed .cnc all
duti -s dev.zed.Zed .gco all
duti -s dev.zed.Zed .gcode all
duti -s dev.zed.Zed .gaml all
duti -s dev.zed.Zed .gms all
duti -s dev.zed.Zed .g all
duti -s dev.zed.Zed .gap all
duti -s dev.zed.Zed .gd all
duti -s dev.zed.Zed .gi all
duti -s dev.zed.Zed .tst all
duti -s dev.zed.Zed .md all
duti -s dev.zed.Zed .gdb all
duti -s dev.zed.Zed .gdbinit all
duti -s dev.zed.Zed .gd all
duti -s dev.zed.Zed .ged all
duti -s dev.zed.Zed .glsl all
duti -s dev.zed.Zed .fp all
duti -s dev.zed.Zed .frag all
duti -s dev.zed.Zed .frg all
duti -s dev.zed.Zed .fs all
duti -s dev.zed.Zed .fsh all
duti -s dev.zed.Zed .fshader all
duti -s dev.zed.Zed .geo all
duti -s dev.zed.Zed .geom all
duti -s dev.zed.Zed .glslf all
duti -s dev.zed.Zed .glslv all
duti -s dev.zed.Zed .gs all
duti -s dev.zed.Zed .gshader all
duti -s dev.zed.Zed .rchit all
duti -s dev.zed.Zed .rmiss all
duti -s dev.zed.Zed .shader all
duti -s dev.zed.Zed .tesc all
duti -s dev.zed.Zed .tese all
duti -s dev.zed.Zed .vert all
duti -s dev.zed.Zed .vrx all
duti -s dev.zed.Zed .vs all
duti -s dev.zed.Zed .vsh all
duti -s dev.zed.Zed .vshader all
duti -s dev.zed.Zed .gn all
duti -s dev.zed.Zed .gni all
duti -s dev.zed.Zed .gn all
duti -s dev.zed.Zed .gsc all
duti -s dev.zed.Zed .csc all
duti -s dev.zed.Zed .gsh all
duti -s dev.zed.Zed .gml all
duti -s dev.zed.Zed .gmi all
duti -s dev.zed.Zed .4gl all
duti -s dev.zed.Zed .per all
duti -s dev.zed.Zed .gs all
duti -s dev.zed.Zed .kid all
duti -s dev.zed.Zed .ebuild all
duti -s dev.zed.Zed .eclass all
duti -s dev.zed.Zed .gbr all
duti -s dev.zed.Zed .cmp all
duti -s dev.zed.Zed .gbl all
duti -s dev.zed.Zed .gbo all
duti -s dev.zed.Zed .gbp all
duti -s dev.zed.Zed .gbs all
duti -s dev.zed.Zed .gko all
duti -s dev.zed.Zed .gml all
duti -s dev.zed.Zed .gpb all
duti -s dev.zed.Zed .gpt all
duti -s dev.zed.Zed .gtl all
duti -s dev.zed.Zed .gto all
duti -s dev.zed.Zed .gtp all
duti -s dev.zed.Zed .gts all
duti -s dev.zed.Zed .ncl all
duti -s dev.zed.Zed .sol all
duti -s dev.zed.Zed .po all
duti -s dev.zed.Zed .pot all
duti -s dev.zed.Zed .feature all
duti -s dev.zed.Zed .story all
duti -s dev.zed.Zed .gitattributes all
duti -s dev.zed.Zed .gitconfig all
duti -s dev.zed.Zed .gitconfig all
duti -s dev.zed.Zed .gitmodules all
duti -s dev.zed.Zed .git-blame-ignore-revs all
duti -s dev.zed.Zed .gleam all
duti -s dev.zed.Zed .gjs all
duti -s dev.zed.Zed .glf all
duti -s dev.zed.Zed .bdf all
duti -s dev.zed.Zed .gp all
duti -s dev.zed.Zed .gnu all
duti -s dev.zed.Zed .gnuplot all
duti -s dev.zed.Zed .p all
duti -s dev.zed.Zed .plot all
duti -s dev.zed.Zed .plt all
duti -s dev.zed.Zed .go all
duti -s dev.zed.Zed .gdnlib all
duti -s dev.zed.Zed .gdns all
duti -s dev.zed.Zed .tres all
duti -s dev.zed.Zed .tscn all
duti -s dev.zed.Zed .golo all
duti -s dev.zed.Zed .gs all
duti -s dev.zed.Zed .gst all
duti -s dev.zed.Zed .gsx all
duti -s dev.zed.Zed .vark all
duti -s dev.zed.Zed .grace all
duti -s dev.zed.Zed .gradle all
duti -s dev.zed.Zed .gradle.kts all
duti -s dev.zed.Zed .gf all
duti -s dev.zed.Zed .gml all
duti -s dev.zed.Zed .graphql all
duti -s dev.zed.Zed .gql all
duti -s dev.zed.Zed .graphqls all
duti -s dev.zed.Zed .dot all
duti -s dev.zed.Zed .gv all
duti -s dev.zed.Zed .groovy all
duti -s dev.zed.Zed .grt all
duti -s dev.zed.Zed .gtpl all
duti -s dev.zed.Zed .gvy all
duti -s dev.zed.Zed .gsp all
duti -s dev.zed.Zed .cfg all
duti -s dev.zed.Zed .hcl all
duti -s dev.zed.Zed .nomad all
duti -s dev.zed.Zed .tf all
duti -s dev.zed.Zed .tfvars all
duti -s dev.zed.Zed .workflow all
duti -s dev.zed.Zed .hlsl all
duti -s dev.zed.Zed .cginc all
duti -s dev.zed.Zed .fx all
duti -s dev.zed.Zed .fxh all
duti -s dev.zed.Zed .hlsli all
duti -s dev.zed.Zed .hocon all
duti -s dev.zed.Zed .scalafix.conf all
duti -s dev.zed.Zed .scalafmt.conf all
duti -s dev.zed.Zed .html all
duti -s dev.zed.Zed .hta all
duti -s dev.zed.Zed .htm all
duti -s dev.zed.Zed .html.hl all
duti -s dev.zed.Zed .inc all
duti -s dev.zed.Zed .xht all
duti -s dev.zed.Zed .xhtml all
duti -s dev.zed.Zed .ecr all
duti -s dev.zed.Zed .eex all
duti -s dev.zed.Zed .html.heex all
duti -s dev.zed.Zed .html.leex all
duti -s dev.zed.Zed .erb all
duti -s dev.zed.Zed .erb.deface all
duti -s dev.zed.Zed .rhtml all
duti -s dev.zed.Zed .phtml all
duti -s dev.zed.Zed .cshtml all
duti -s dev.zed.Zed .razor all
duti -s dev.zed.Zed .http all
duti -s dev.zed.Zed .hxml all
duti -s dev.zed.Zed .hack all
duti -s dev.zed.Zed .hh all
duti -s dev.zed.Zed .hhi all
duti -s dev.zed.Zed .php all
duti -s dev.zed.Zed .haml all
duti -s dev.zed.Zed .haml.deface all
duti -s dev.zed.Zed .handlebars all
duti -s dev.zed.Zed .hbs all
duti -s dev.zed.Zed .hb all
duti -s dev.zed.Zed .hs all
duti -s dev.zed.Zed .hs-boot all
duti -s dev.zed.Zed .hsc all
duti -s dev.zed.Zed .hx all
duti -s dev.zed.Zed .hxsl all
duti -s dev.zed.Zed .q all
duti -s dev.zed.Zed .hql all
duti -s dev.zed.Zed .hc all
duti -s dev.zed.Zed .hy all
duti -s dev.zed.Zed .bf all
duti -s dev.zed.Zed .pro all
duti -s dev.zed.Zed .dlm all
duti -s dev.zed.Zed .ipf all
duti -s dev.zed.Zed .ini all
duti -s dev.zed.Zed .cfg all
duti -s dev.zed.Zed .cnf all
duti -s dev.zed.Zed .dof all
duti -s dev.zed.Zed .lektorproject all
duti -s dev.zed.Zed .prefs all
duti -s dev.zed.Zed .pro all
duti -s dev.zed.Zed .properties all
duti -s dev.zed.Zed .url all
duti -s dev.zed.Zed .coveragerc all
duti -s dev.zed.Zed .flake8 all
duti -s dev.zed.Zed .pylintrc all
duti -s dev.zed.Zed .irclog all
duti -s dev.zed.Zed .weechatlog all
duti -s dev.zed.Zed .idr all
duti -s dev.zed.Zed .lidr all
duti -s dev.zed.Zed .gitignore all
duti -s dev.zed.Zed .atomignore all
duti -s dev.zed.Zed .babelignore all
duti -s dev.zed.Zed .bzrignore all
duti -s dev.zed.Zed .coffeelintignore all
duti -s dev.zed.Zed .cvsignore all
duti -s dev.zed.Zed .dockerignore all
duti -s dev.zed.Zed .eleventyignore all
duti -s dev.zed.Zed .eslintignore all
duti -s dev.zed.Zed .gitignore all
duti -s dev.zed.Zed .markdownlintignore all
duti -s dev.zed.Zed .nodemonignore all
duti -s dev.zed.Zed .npmignore all
duti -s dev.zed.Zed .prettierignore all
duti -s dev.zed.Zed .stylelintignore all
duti -s dev.zed.Zed .vercelignore all
duti -s dev.zed.Zed .vscodeignore all
duti -s dev.zed.Zed .ijm all
duti -s dev.zed.Zed .imba all
duti -s dev.zed.Zed .ni all
duti -s dev.zed.Zed .i7x all
duti -s dev.zed.Zed .ink all
duti -s dev.zed.Zed .iss all
duti -s dev.zed.Zed .isl all
duti -s dev.zed.Zed .io all
duti -s dev.zed.Zed .ik all
duti -s dev.zed.Zed .thy all
duti -s dev.zed.Zed .ijs all
duti -s dev.zed.Zed .jcl all
duti -s dev.zed.Zed .flex all
duti -s dev.zed.Zed .jflex all
duti -s dev.zed.Zed .json all
duti -s dev.zed.Zed .4DForm all
duti -s dev.zed.Zed .4DProject all
duti -s dev.zed.Zed .avsc all
duti -s dev.zed.Zed .geojson all
duti -s dev.zed.Zed .gltf all
duti -s dev.zed.Zed .har all
duti -s dev.zed.Zed .ice all
duti -s dev.zed.Zed .JSON-tmLanguage all
duti -s dev.zed.Zed .jsonl all
duti -s dev.zed.Zed .mcmeta all
duti -s dev.zed.Zed .tfstate all
duti -s dev.zed.Zed .tfstate.backup all
duti -s dev.zed.Zed .topojson all
duti -s dev.zed.Zed .webapp all
duti -s dev.zed.Zed .webmanifest all
duti -s dev.zed.Zed .yy all
duti -s dev.zed.Zed .yyp all
duti -s dev.zed.Zed .all-contributorsrc all
duti -s dev.zed.Zed .arcconfig all
duti -s dev.zed.Zed .auto-changelog all
duti -s dev.zed.Zed .c8rc all
duti -s dev.zed.Zed .htmlhintrc all
duti -s dev.zed.Zed .imgbotconfig all
duti -s dev.zed.Zed .nycrc all
duti -s dev.zed.Zed .tern-config all
duti -s dev.zed.Zed .tern-project all
duti -s dev.zed.Zed .watchmanconfig all
duti -s dev.zed.Zed .jsonc all
duti -s dev.zed.Zed .code-snippets all
duti -s dev.zed.Zed .code-workspace all
duti -s dev.zed.Zed .sublime-build all
duti -s dev.zed.Zed .sublime-commands all
duti -s dev.zed.Zed .sublime-completions all
duti -s dev.zed.Zed .sublime-keymap all
duti -s dev.zed.Zed .sublime-macro all
duti -s dev.zed.Zed .sublime-menu all
duti -s dev.zed.Zed .sublime-mousemap all
duti -s dev.zed.Zed .sublime-project all
duti -s dev.zed.Zed .sublime-settings all
duti -s dev.zed.Zed .sublime-theme all
duti -s dev.zed.Zed .sublime-workspace all
duti -s dev.zed.Zed .sublime_metrics all
duti -s dev.zed.Zed .sublime_session all
duti -s dev.zed.Zed .babelrc all
duti -s dev.zed.Zed .devcontainer.json all
duti -s dev.zed.Zed .eslintrc.json all
duti -s dev.zed.Zed .jscsrc all
duti -s dev.zed.Zed .jshintrc all
duti -s dev.zed.Zed .jslintrc all
duti -s dev.zed.Zed .swcrc all
duti -s dev.zed.Zed .json5 all
duti -s dev.zed.Zed .jsonld all
duti -s dev.zed.Zed .jq all
duti -s dev.zed.Zed .janet all
duti -s dev.zed.Zed .j all
duti -s dev.zed.Zed .java all
duti -s dev.zed.Zed .jav all
duti -s dev.zed.Zed .jsh all
duti -s dev.zed.Zed .properties all
duti -s dev.zed.Zed .jsp all
duti -s dev.zed.Zed .tag all
duti -s dev.zed.Zed .js all
duti -s dev.zed.Zed ._js all
duti -s dev.zed.Zed .bones all
duti -s dev.zed.Zed .cjs all
duti -s dev.zed.Zed .es all
duti -s dev.zed.Zed .es6 all
duti -s dev.zed.Zed .frag all
duti -s dev.zed.Zed .gs all
duti -s dev.zed.Zed .jake all
duti -s dev.zed.Zed .javascript all
duti -s dev.zed.Zed .jsb all
duti -s dev.zed.Zed .jscad all
duti -s dev.zed.Zed .jsfl all
duti -s dev.zed.Zed .jslib all
duti -s dev.zed.Zed .jsm all
duti -s dev.zed.Zed .jspre all
duti -s dev.zed.Zed .jss all
duti -s dev.zed.Zed .jsx all
duti -s dev.zed.Zed .mjs all
duti -s dev.zed.Zed .njs all
duti -s dev.zed.Zed .pac all
duti -s dev.zed.Zed .sjs all
duti -s dev.zed.Zed .ssjs all
duti -s dev.zed.Zed .xsjs all
duti -s dev.zed.Zed .xsjslib all
duti -s dev.zed.Zed .js.erb all
duti -s dev.zed.Zed .snap all
duti -s dev.zed.Zed .mps all
duti -s dev.zed.Zed .mpl all
duti -s dev.zed.Zed .msd all
duti -s dev.zed.Zed .jinja all
duti -s dev.zed.Zed .j2 all
duti -s dev.zed.Zed .jinja2 all
duti -s dev.zed.Zed .jison all
duti -s dev.zed.Zed .jisonlex all
duti -s dev.zed.Zed .ol all
duti -s dev.zed.Zed .iol all
duti -s dev.zed.Zed .jsonnet all
duti -s dev.zed.Zed .libsonnet all
duti -s dev.zed.Zed .jl all
duti -s dev.zed.Zed .ipynb all
duti -s dev.zed.Zed .krl all
duti -s dev.zed.Zed .ksy all
duti -s dev.zed.Zed .kak all
duti -s dev.zed.Zed .ks all
duti -s dev.zed.Zed .kicad_pcb all
duti -s dev.zed.Zed .kicad_mod all
duti -s dev.zed.Zed .kicad_wks all
duti -s dev.zed.Zed .brd all
duti -s dev.zed.Zed .kicad_sch all
duti -s dev.zed.Zed .sch all
duti -s dev.zed.Zed .ks all
duti -s dev.zed.Zed .kit all
duti -s dev.zed.Zed .kt all
duti -s dev.zed.Zed .ktm all
duti -s dev.zed.Zed .kts all
duti -s dev.zed.Zed .csl all
duti -s dev.zed.Zed .kql all
duti -s dev.zed.Zed .lfe all
duti -s dev.zed.Zed .ll all
duti -s dev.zed.Zed .lol all
duti -s dev.zed.Zed .lsl all
duti -s dev.zed.Zed .lslp all
duti -s dev.zed.Zed .asy all
duti -s dev.zed.Zed .lvproj all
duti -s dev.zed.Zed .lvclass all
duti -s dev.zed.Zed .lvlib all
duti -s dev.zed.Zed .lark all
duti -s dev.zed.Zed .lasso all
duti -s dev.zed.Zed .las all
duti -s dev.zed.Zed .lasso8 all
duti -s dev.zed.Zed .lasso9 all
duti -s dev.zed.Zed .latte all
duti -s dev.zed.Zed .lean all
duti -s dev.zed.Zed .hlean all
duti -s dev.zed.Zed .lean all
duti -s dev.zed.Zed .less all
duti -s dev.zed.Zed .l all
duti -s dev.zed.Zed .lex all
duti -s dev.zed.Zed .ligo all
duti -s dev.zed.Zed .ly all
duti -s dev.zed.Zed .ily all
duti -s dev.zed.Zed .b all
duti -s dev.zed.Zed .m all
duti -s dev.zed.Zed .ld all
duti -s dev.zed.Zed .lds all
duti -s dev.zed.Zed .x all
duti -s dev.zed.Zed .mod all
duti -s dev.zed.Zed .liquid all
duti -s dev.zed.Zed .lagda all
duti -s dev.zed.Zed .litcoffee all
duti -s dev.zed.Zed .coffee.md all
duti -s dev.zed.Zed .lhs all
duti -s dev.zed.Zed .ls all
duti -s dev.zed.Zed ._ls all
duti -s dev.zed.Zed .xm all
duti -s dev.zed.Zed .x all
duti -s dev.zed.Zed .xi all
duti -s dev.zed.Zed .lgt all
duti -s dev.zed.Zed .logtalk all
duti -s dev.zed.Zed .lkml all
duti -s dev.zed.Zed .lookml all
duti -s dev.zed.Zed .ls all
duti -s dev.zed.Zed .lua all
duti -s dev.zed.Zed .fcgi all
duti -s dev.zed.Zed .nse all
duti -s dev.zed.Zed .p8 all
duti -s dev.zed.Zed .pd_lua all
duti -s dev.zed.Zed .rbxs all
duti -s dev.zed.Zed .rockspec all
duti -s dev.zed.Zed .wlua all
duti -s dev.zed.Zed .luacheckrc all
duti -s dev.zed.Zed .mumps all
duti -s dev.zed.Zed .m all
duti -s dev.zed.Zed .m4 all
duti -s dev.zed.Zed .mc all
duti -s dev.zed.Zed .m4 all
duti -s dev.zed.Zed .matlab all
duti -s dev.zed.Zed .m all
duti -s dev.zed.Zed .ms all
duti -s dev.zed.Zed .mcr all
duti -s dev.zed.Zed .mdx all
duti -s dev.zed.Zed .mlir all
duti -s dev.zed.Zed .mq4 all
duti -s dev.zed.Zed .mqh all
duti -s dev.zed.Zed .mq5 all
duti -s dev.zed.Zed .mqh all
duti -s dev.zed.Zed .mtml all
duti -s dev.zed.Zed .muf all
duti -s dev.zed.Zed .m all
duti -s dev.zed.Zed .m2 all
duti -s dev.zed.Zed .mak all
duti -s dev.zed.Zed .d all
duti -s dev.zed.Zed .make all
duti -s dev.zed.Zed .makefile all
duti -s dev.zed.Zed .mk all
duti -s dev.zed.Zed .mkfile all
duti -s dev.zed.Zed .mako all
duti -s dev.zed.Zed .mao all
duti -s dev.zed.Zed .md all
duti -s dev.zed.Zed .livemd all
duti -s dev.zed.Zed .markdown all
duti -s dev.zed.Zed .mdown all
duti -s dev.zed.Zed .mdwn all
duti -s dev.zed.Zed .mkd all
duti -s dev.zed.Zed .mkdn all
duti -s dev.zed.Zed .mkdown all
duti -s dev.zed.Zed .ronn all
duti -s dev.zed.Zed .scd all
duti -s dev.zed.Zed .workbook all
duti -s dev.zed.Zed .marko all
duti -s dev.zed.Zed .mask all
duti -s dev.zed.Zed .mathematica all
duti -s dev.zed.Zed .cdf all
duti -s dev.zed.Zed .m all
duti -s dev.zed.Zed .ma all
duti -s dev.zed.Zed .mt all
duti -s dev.zed.Zed .nb all
duti -s dev.zed.Zed .nbp all
duti -s dev.zed.Zed .wl all
duti -s dev.zed.Zed .wlt all
duti -s dev.zed.Zed .maxpat all
duti -s dev.zed.Zed .maxhelp all
duti -s dev.zed.Zed .maxproj all
duti -s dev.zed.Zed .mxt all
duti -s dev.zed.Zed .pat all
duti -s dev.zed.Zed .m all
duti -s dev.zed.Zed .moo all
duti -s dev.zed.Zed .mmd all
duti -s dev.zed.Zed .mermaid all
duti -s dev.zed.Zed .metal all
duti -s dev.zed.Zed .dsp all
duti -s dev.zed.Zed .sln all
duti -s dev.zed.Zed .minid all
duti -s dev.zed.Zed .yaml all
duti -s dev.zed.Zed .yml all
duti -s dev.zed.Zed .mint all
duti -s dev.zed.Zed .druby all
duti -s dev.zed.Zed .duby all
duti -s dev.zed.Zed .mirah all
duti -s dev.zed.Zed .mo all
duti -s dev.zed.Zed .mod all
duti -s dev.zed.Zed .i3 all
duti -s dev.zed.Zed .ig all
duti -s dev.zed.Zed .m3 all
duti -s dev.zed.Zed .mg all
duti -s dev.zed.Zed .mms all
duti -s dev.zed.Zed .mmk all
duti -s dev.zed.Zed .monkey all
duti -s dev.zed.Zed .monkey2 all
duti -s dev.zed.Zed .mc all
duti -s dev.zed.Zed .moo all
duti -s dev.zed.Zed .moon all
duti -s dev.zed.Zed .mo all
duti -s dev.zed.Zed .asm all
duti -s dev.zed.Zed .i all
duti -s dev.zed.Zed .inc all
duti -s dev.zed.Zed .s all
duti -s dev.zed.Zed .x68 all
duti -s dev.zed.Zed .move all
duti -s dev.zed.Zed .muse all
duti -s dev.zed.Zed .mustache all
duti -s dev.zed.Zed .myt all
duti -s dev.zed.Zed .nasl all
duti -s dev.zed.Zed .inc all
duti -s dev.zed.Zed .ncl all
duti -s dev.zed.Zed .neon all
duti -s dev.zed.Zed .nl all
duti -s dev.zed.Zed .npmrc all
duti -s dev.zed.Zed .nsi all
duti -s dev.zed.Zed .nsh all
duti -s dev.zed.Zed .nss all
duti -s dev.zed.Zed .nas all
duti -s dev.zed.Zed .ne all
duti -s dev.zed.Zed .nearley all
duti -s dev.zed.Zed .n all
duti -s dev.zed.Zed .axs all
duti -s dev.zed.Zed .axi all
duti -s dev.zed.Zed .axs.erb all
duti -s dev.zed.Zed .axi.erb all
duti -s dev.zed.Zed .nlogo all
duti -s dev.zed.Zed .nl all
duti -s dev.zed.Zed .lisp all
duti -s dev.zed.Zed .lsp all
duti -s dev.zed.Zed .nf all
duti -s dev.zed.Zed .nginx all
duti -s dev.zed.Zed .nginxconf all
duti -s dev.zed.Zed .vhost all
duti -s dev.zed.Zed .nim all
duti -s dev.zed.Zed .nim.cfg all
duti -s dev.zed.Zed .nimble all
duti -s dev.zed.Zed .nimrod all
duti -s dev.zed.Zed .nims all
duti -s dev.zed.Zed .ninja all
duti -s dev.zed.Zed .nit all
duti -s dev.zed.Zed .nix all
duti -s dev.zed.Zed .nu all
duti -s dev.zed.Zed .numpy all
duti -s dev.zed.Zed .numpyw all
duti -s dev.zed.Zed .numsc all
duti -s dev.zed.Zed .njk all
duti -s dev.zed.Zed .nu all
duti -s dev.zed.Zed .json all
duti -s dev.zed.Zed .yaml all
duti -s dev.zed.Zed .yml all
duti -s dev.zed.Zed .json all
duti -s dev.zed.Zed .yaml all
duti -s dev.zed.Zed .yml all
duti -s dev.zed.Zed .ml all
duti -s dev.zed.Zed .eliom all
duti -s dev.zed.Zed .eliomi all
duti -s dev.zed.Zed .ml4 all
duti -s dev.zed.Zed .mli all
duti -s dev.zed.Zed .mll all
duti -s dev.zed.Zed .mly all
duti -s dev.zed.Zed .objdump all
duti -s dev.zed.Zed .odin all
duti -s dev.zed.Zed .cls all
duti -s dev.zed.Zed .m all
duti -s dev.zed.Zed .h all
duti -s dev.zed.Zed .mm all
duti -s dev.zed.Zed .j all
duti -s dev.zed.Zed .sj all
duti -s dev.zed.Zed .odin all
duti -s dev.zed.Zed .omgrofl all
duti -s dev.zed.Zed .opa all
duti -s dev.zed.Zed .opal all
duti -s dev.zed.Zed .rego all
duti -s dev.zed.Zed .cl all
duti -s dev.zed.Zed .opencl all
duti -s dev.zed.Zed .p all
duti -s dev.zed.Zed .cls all
duti -s dev.zed.Zed .w all
duti -s dev.zed.Zed .qasm all
duti -s dev.zed.Zed .scad all
duti -s dev.zed.Zed .plist all
duti -s dev.zed.Zed .glyphs all
duti -s dev.zed.Zed .fea all
duti -s dev.zed.Zed .ackrc all
duti -s dev.zed.Zed .rspec all
duti -s dev.zed.Zed .yardopts all
duti -s dev.zed.Zed .org all
duti -s dev.zed.Zed .ox all
duti -s dev.zed.Zed .oxh all
duti -s dev.zed.Zed .oxo all
duti -s dev.zed.Zed .oxygene all
duti -s dev.zed.Zed .oz all
duti -s dev.zed.Zed .p4 all
duti -s dev.zed.Zed .pddl all
duti -s dev.zed.Zed .pegjs all
duti -s dev.zed.Zed .php all
duti -s dev.zed.Zed .aw all
duti -s dev.zed.Zed .ctp all
duti -s dev.zed.Zed .fcgi all
duti -s dev.zed.Zed .inc all
duti -s dev.zed.Zed .php3 all
duti -s dev.zed.Zed .php4 all
duti -s dev.zed.Zed .php5 all
duti -s dev.zed.Zed .phps all
duti -s dev.zed.Zed .phpt all
duti -s dev.zed.Zed .php all
duti -s dev.zed.Zed .php_cs all
duti -s dev.zed.Zed .php_cs.dist all
duti -s dev.zed.Zed .pls all
duti -s dev.zed.Zed .bdy all
duti -s dev.zed.Zed .ddl all
duti -s dev.zed.Zed .fnc all
duti -s dev.zed.Zed .pck all
duti -s dev.zed.Zed .pkb all
duti -s dev.zed.Zed .pks all
duti -s dev.zed.Zed .plb all
duti -s dev.zed.Zed .plsql all
duti -s dev.zed.Zed .prc all
duti -s dev.zed.Zed .spc all
duti -s dev.zed.Zed .sql all
duti -s dev.zed.Zed .tpb all
duti -s dev.zed.Zed .tps all
duti -s dev.zed.Zed .trg all
duti -s dev.zed.Zed .vw all
duti -s dev.zed.Zed .pgsql all
duti -s dev.zed.Zed .sql all
duti -s dev.zed.Zed .pov all
duti -s dev.zed.Zed .inc all
duti -s dev.zed.Zed .pact all
duti -s dev.zed.Zed .pan all
duti -s dev.zed.Zed .psc all
duti -s dev.zed.Zed .parrot all
duti -s dev.zed.Zed .pasm all
duti -s dev.zed.Zed .pir all
duti -s dev.zed.Zed .pas all
duti -s dev.zed.Zed .dfm all
duti -s dev.zed.Zed .dpr all
duti -s dev.zed.Zed .inc all
duti -s dev.zed.Zed .lpr all
duti -s dev.zed.Zed .pascal all
duti -s dev.zed.Zed .pp all
duti -s dev.zed.Zed .pwn all
duti -s dev.zed.Zed .inc all
duti -s dev.zed.Zed .sma all
duti -s dev.zed.Zed .pep all
duti -s dev.zed.Zed .pl all
duti -s dev.zed.Zed .al all
duti -s dev.zed.Zed .cgi all
duti -s dev.zed.Zed .fcgi all
duti -s dev.zed.Zed .perl all
duti -s dev.zed.Zed .ph all
duti -s dev.zed.Zed .plx all
duti -s dev.zed.Zed .pm all
duti -s dev.zed.Zed .psgi all
duti -s dev.zed.Zed .t all
duti -s dev.zed.Zed .latexmkrc all
duti -s dev.zed.Zed .pic all
duti -s dev.zed.Zed .chem all
duti -s dev.zed.Zed .pkl all
duti -s dev.zed.Zed .l all
duti -s dev.zed.Zed .pig all
duti -s dev.zed.Zed .pike all
duti -s dev.zed.Zed .pmod all
duti -s dev.zed.Zed .puml all
duti -s dev.zed.Zed .iuml all
duti -s dev.zed.Zed .plantuml all
duti -s dev.zed.Zed .pod all
duti -s dev.zed.Zed .pod all
duti -s dev.zed.Zed .pod6 all
duti -s dev.zed.Zed .pogo all
duti -s dev.zed.Zed .polar all
duti -s dev.zed.Zed .pony all
duti -s dev.zed.Zed .por all
duti -s dev.zed.Zed .pcss all
duti -s dev.zed.Zed .postcss all
duti -s dev.zed.Zed .ps all
duti -s dev.zed.Zed .eps all
duti -s dev.zed.Zed .epsi all
duti -s dev.zed.Zed .pfa all
duti -s dev.zed.Zed .pbt all
duti -s dev.zed.Zed .sra all
duti -s dev.zed.Zed .sru all
duti -s dev.zed.Zed .srw all
duti -s dev.zed.Zed .ps1 all
duti -s dev.zed.Zed .psd1 all
duti -s dev.zed.Zed .psm1 all
duti -s dev.zed.Zed .praat all
duti -s dev.zed.Zed .prisma all
duti -s dev.zed.Zed .pde all
duti -s dev.zed.Zed .pro all
duti -s dev.zed.Zed .pl all
duti -s dev.zed.Zed .plt all
duti -s dev.zed.Zed .pro all
duti -s dev.zed.Zed .prolog all
duti -s dev.zed.Zed .yap all
duti -s dev.zed.Zed .pml all
duti -s dev.zed.Zed .spin all
duti -s dev.zed.Zed .proto all
duti -s dev.zed.Zed .textproto all
duti -s dev.zed.Zed .pbt all
duti -s dev.zed.Zed .pbtxt all
duti -s dev.zed.Zed .asc all
duti -s dev.zed.Zed .pub all
duti -s dev.zed.Zed .jade all
duti -s dev.zed.Zed .pug all
duti -s dev.zed.Zed .pp all
duti -s dev.zed.Zed .pd all
duti -s dev.zed.Zed .pb all
duti -s dev.zed.Zed .pbi all
duti -s dev.zed.Zed .purs all
duti -s dev.zed.Zed .arr all
duti -s dev.zed.Zed .py all
duti -s dev.zed.Zed .cgi all
duti -s dev.zed.Zed .fcgi all
duti -s dev.zed.Zed .gyp all
duti -s dev.zed.Zed .gypi all
duti -s dev.zed.Zed .lmi all
duti -s dev.zed.Zed .py3 all
duti -s dev.zed.Zed .pyde all
duti -s dev.zed.Zed .pyi all
duti -s dev.zed.Zed .pyp all
duti -s dev.zed.Zed .pyt all
duti -s dev.zed.Zed .pyw all
duti -s dev.zed.Zed .rpy all
duti -s dev.zed.Zed .spec all
duti -s dev.zed.Zed .tac all
duti -s dev.zed.Zed .wsgi all
duti -s dev.zed.Zed .xpy all
duti -s dev.zed.Zed .gclient all
duti -s dev.zed.Zed .pytb all
duti -s dev.zed.Zed .qs all
duti -s dev.zed.Zed .qml all
duti -s dev.zed.Zed .qbs all
duti -s dev.zed.Zed .pro all
duti -s dev.zed.Zed .pri all
duti -s dev.zed.Zed .qs all
duti -s dev.zed.Zed .r all
duti -s dev.zed.Zed .rd all
duti -s dev.zed.Zed .rsx all
duti -s dev.zed.Zed .Rprofile all
duti -s dev.zed.Zed .raml all
duti -s dev.zed.Zed .rbs all
duti -s dev.zed.Zed .rdoc all
duti -s dev.zed.Zed .rbbas all
duti -s dev.zed.Zed .rbfrm all
duti -s dev.zed.Zed .rbmnu all
duti -s dev.zed.Zed .rbres all
duti -s dev.zed.Zed .rbtbar all
duti -s dev.zed.Zed .rbuistate all
duti -s dev.zed.Zed .rexx all
duti -s dev.zed.Zed .pprx all
duti -s dev.zed.Zed .rex all
duti -s dev.zed.Zed .qmd all
duti -s dev.zed.Zed .rmd all
duti -s dev.zed.Zed .x all
duti -s dev.zed.Zed .rpgle all
duti -s dev.zed.Zed .sqlrpgle all
duti -s dev.zed.Zed .spec all
duti -s dev.zed.Zed .rnh all
duti -s dev.zed.Zed .rno all
duti -s dev.zed.Zed .rkt all
duti -s dev.zed.Zed .rktd all
duti -s dev.zed.Zed .rktl all
duti -s dev.zed.Zed .scrbl all
duti -s dev.zed.Zed .rl all
duti -s dev.zed.Zed .6pl all
duti -s dev.zed.Zed .6pm all
duti -s dev.zed.Zed .nqp all
duti -s dev.zed.Zed .p6 all
duti -s dev.zed.Zed .p6l all
duti -s dev.zed.Zed .p6m all
duti -s dev.zed.Zed .pl all
duti -s dev.zed.Zed .pl6 all
duti -s dev.zed.Zed .pm all
duti -s dev.zed.Zed .pm6 all
duti -s dev.zed.Zed .raku all
duti -s dev.zed.Zed .rakumod all
duti -s dev.zed.Zed .t all
duti -s dev.zed.Zed .rsc all
duti -s dev.zed.Zed .raw all
duti -s dev.zed.Zed .res all
duti -s dev.zed.Zed .inputrc all
duti -s dev.zed.Zed .re all
duti -s dev.zed.Zed .rei all
duti -s dev.zed.Zed .religo all
duti -s dev.zed.Zed .reb all
duti -s dev.zed.Zed .r all
duti -s dev.zed.Zed .r2 all
duti -s dev.zed.Zed .r3 all
duti -s dev.zed.Zed .rebol all
duti -s dev.zed.Zed .red all
duti -s dev.zed.Zed .reds all
duti -s dev.zed.Zed .cw all
duti -s dev.zed.Zed .regexp all
duti -s dev.zed.Zed .regex all
duti -s dev.zed.Zed .rpy all
duti -s dev.zed.Zed .rs all
duti -s dev.zed.Zed .rsh all
duti -s dev.zed.Zed .r all
duti -s dev.zed.Zed .rtf all
duti -s dev.zed.Zed .ring all
duti -s dev.zed.Zed .riot all
duti -s dev.zed.Zed .robot all
duti -s dev.zed.Zed .roff all
duti -s dev.zed.Zed .1 all
duti -s dev.zed.Zed .1in all
duti -s dev.zed.Zed .1m all
duti -s dev.zed.Zed .1x all
duti -s dev.zed.Zed .2 all
duti -s dev.zed.Zed .3 all
duti -s dev.zed.Zed .3in all
duti -s dev.zed.Zed .3m all
duti -s dev.zed.Zed .3p all
duti -s dev.zed.Zed .3pm all
duti -s dev.zed.Zed .3qt all
duti -s dev.zed.Zed .3x all
duti -s dev.zed.Zed .4 all
duti -s dev.zed.Zed .5 all
duti -s dev.zed.Zed .6 all
duti -s dev.zed.Zed .7 all
duti -s dev.zed.Zed .8 all
duti -s dev.zed.Zed .9 all
duti -s dev.zed.Zed .l all
duti -s dev.zed.Zed .man all
duti -s dev.zed.Zed .mdoc all
duti -s dev.zed.Zed .me all
duti -s dev.zed.Zed .ms all
duti -s dev.zed.Zed .n all
duti -s dev.zed.Zed .nr all
duti -s dev.zed.Zed .rno all
duti -s dev.zed.Zed .tmac all
duti -s dev.zed.Zed .1 all
duti -s dev.zed.Zed .1in all
duti -s dev.zed.Zed .1m all
duti -s dev.zed.Zed .1x all
duti -s dev.zed.Zed .2 all
duti -s dev.zed.Zed .3 all
duti -s dev.zed.Zed .3in all
duti -s dev.zed.Zed .3m all
duti -s dev.zed.Zed .3p all
duti -s dev.zed.Zed .3pm all
duti -s dev.zed.Zed .3qt all
duti -s dev.zed.Zed .3x all
duti -s dev.zed.Zed .4 all
duti -s dev.zed.Zed .5 all
duti -s dev.zed.Zed .6 all
duti -s dev.zed.Zed .7 all
duti -s dev.zed.Zed .8 all
duti -s dev.zed.Zed .9 all
duti -s dev.zed.Zed .man all
duti -s dev.zed.Zed .mdoc all
duti -s dev.zed.Zed .rg all
duti -s dev.zed.Zed .rsc all
duti -s dev.zed.Zed .rb all
duti -s dev.zed.Zed .builder all
duti -s dev.zed.Zed .eye all
duti -s dev.zed.Zed .fcgi all
duti -s dev.zed.Zed .gemspec all
duti -s dev.zed.Zed .god all
duti -s dev.zed.Zed .jbuilder all
duti -s dev.zed.Zed .mspec all
duti -s dev.zed.Zed .pluginspec all
duti -s dev.zed.Zed .podspec all
duti -s dev.zed.Zed .prawn all
duti -s dev.zed.Zed .rabl all
duti -s dev.zed.Zed .rake all
duti -s dev.zed.Zed .rbi all
duti -s dev.zed.Zed .rbuild all
duti -s dev.zed.Zed .rbw all
duti -s dev.zed.Zed .rbx all
duti -s dev.zed.Zed .ru all
duti -s dev.zed.Zed .ruby all
duti -s dev.zed.Zed .spec all
duti -s dev.zed.Zed .thor all
duti -s dev.zed.Zed .watchr all
duti -s dev.zed.Zed .irbrc all
duti -s dev.zed.Zed .pryrc all
duti -s dev.zed.Zed .simplecov all
duti -s dev.zed.Zed .rs all
duti -s dev.zed.Zed .rs.in all
duti -s dev.zed.Zed .sas all
duti -s dev.zed.Zed .scss all
duti -s dev.zed.Zed .te all
duti -s dev.zed.Zed .smt2 all
duti -s dev.zed.Zed .smt all
duti -s dev.zed.Zed .sparql all
duti -s dev.zed.Zed .rq all
duti -s dev.zed.Zed .sqf all
duti -s dev.zed.Zed .hqf all
duti -s dev.zed.Zed .sql all
duti -s dev.zed.Zed .cql all
duti -s dev.zed.Zed .ddl all
duti -s dev.zed.Zed .inc all
duti -s dev.zed.Zed .mysql all
duti -s dev.zed.Zed .prc all
duti -s dev.zed.Zed .tab all
duti -s dev.zed.Zed .udf all
duti -s dev.zed.Zed .viw all
duti -s dev.zed.Zed .sql all
duti -s dev.zed.Zed .db2 all
duti -s dev.zed.Zed .srt all
duti -s dev.zed.Zed .star all
duti -s dev.zed.Zed .stl all
duti -s dev.zed.Zed .ston all
duti -s dev.zed.Zed .svg all
duti -s dev.zed.Zed .i all
duti -s dev.zed.Zed .sage all
duti -s dev.zed.Zed .sagews all
duti -s dev.zed.Zed .sls all
duti -s dev.zed.Zed .sass all
duti -s dev.zed.Zed .scala all
duti -s dev.zed.Zed .kojo all
duti -s dev.zed.Zed .sbt all
duti -s dev.zed.Zed .sc all
duti -s dev.zed.Zed .scaml all
duti -s dev.zed.Zed .scenic all
duti -s dev.zed.Zed .scm all
duti -s dev.zed.Zed .sch all
duti -s dev.zed.Zed .sld all
duti -s dev.zed.Zed .sls all
duti -s dev.zed.Zed .sps all
duti -s dev.zed.Zed .ss all
duti -s dev.zed.Zed .sci all
duti -s dev.zed.Zed .sce all
duti -s dev.zed.Zed .tst all
duti -s dev.zed.Zed .self all
duti -s dev.zed.Zed .shader all
duti -s dev.zed.Zed .sh all
duti -s dev.zed.Zed .bash all
duti -s dev.zed.Zed .bats all
duti -s dev.zed.Zed .cgi all
duti -s dev.zed.Zed .command all
duti -s dev.zed.Zed .fcgi all
duti -s dev.zed.Zed .ksh all
duti -s dev.zed.Zed .sh.in all
duti -s dev.zed.Zed .tmux all
duti -s dev.zed.Zed .tool all
duti -s dev.zed.Zed .trigger all
duti -s dev.zed.Zed .zsh all
duti -s dev.zed.Zed .zsh-theme all
duti -s dev.zed.Zed .bash_aliases all
duti -s dev.zed.Zed .bash_functions all
duti -s dev.zed.Zed .bash_history all
duti -s dev.zed.Zed .bash_logout all
duti -s dev.zed.Zed .bash_profile all
duti -s dev.zed.Zed .bashrc all
duti -s dev.zed.Zed .cshrc all
duti -s dev.zed.Zed .flaskenv all
duti -s dev.zed.Zed .kshrc all
duti -s dev.zed.Zed .login all
duti -s dev.zed.Zed .profile all
duti -s dev.zed.Zed .zlogin all
duti -s dev.zed.Zed .zlogout all
duti -s dev.zed.Zed .zprofile all
duti -s dev.zed.Zed .zshenv all
duti -s dev.zed.Zed .zshrc all
duti -s dev.zed.Zed .shellcheckrc all
duti -s dev.zed.Zed .sh-session all
duti -s dev.zed.Zed .shen all
duti -s dev.zed.Zed .sieve all
duti -s dev.zed.Zed .sfv all
duti -s dev.zed.Zed .sl all
duti -s dev.zed.Zed .ice all
duti -s dev.zed.Zed .slim all
duti -s dev.zed.Zed .cocci all
duti -s dev.zed.Zed .smali all
duti -s dev.zed.Zed .st all
duti -s dev.zed.Zed .cs all
duti -s dev.zed.Zed .tpl all
duti -s dev.zed.Zed .smithy all
duti -s dev.zed.Zed .smk all
duti -s dev.zed.Zed .snakefile all
duti -s dev.zed.Zed .sol all
duti -s dev.zed.Zed .sp all
duti -s dev.zed.Zed .inc all
duti -s dev.zed.Zed .sfd all
duti -s dev.zed.Zed .nut all
duti -s dev.zed.Zed .stan all
duti -s dev.zed.Zed .ml all
duti -s dev.zed.Zed .fun all
duti -s dev.zed.Zed .sig all
duti -s dev.zed.Zed .sml all
duti -s dev.zed.Zed .bzl all
duti -s dev.zed.Zed .star all
duti -s dev.zed.Zed .do all
duti -s dev.zed.Zed .ado all
duti -s dev.zed.Zed .doh all
duti -s dev.zed.Zed .ihlp all
duti -s dev.zed.Zed .mata all
duti -s dev.zed.Zed .matah all
duti -s dev.zed.Zed .sthlp all
duti -s dev.zed.Zed .st all
duti -s dev.zed.Zed .styl all
duti -s dev.zed.Zed .srt all
duti -s dev.zed.Zed .sss all
duti -s dev.zed.Zed .sc all
duti -s dev.zed.Zed .scd all
duti -s dev.zed.Zed .svelte all
duti -s dev.zed.Zed .sw all
duti -s dev.zed.Zed .rnw all
duti -s dev.zed.Zed .swift all
duti -s dev.zed.Zed .sv all
duti -s dev.zed.Zed .svh all
duti -s dev.zed.Zed .vh all
duti -s dev.zed.Zed .8xp all
duti -s dev.zed.Zed .8xk all
duti -s dev.zed.Zed .8xk.txt all
duti -s dev.zed.Zed .8xp.txt all
duti -s dev.zed.Zed .tlv all
duti -s dev.zed.Zed .tla all
duti -s dev.zed.Zed .toml all
duti -s dev.zed.Zed .sql all
duti -s dev.zed.Zed .tsv all
duti -s dev.zed.Zed .tsx all
duti -s dev.zed.Zed .txl all
duti -s dev.zed.Zed .talon all
duti -s dev.zed.Zed .tcl all
duti -s dev.zed.Zed .adp all
duti -s dev.zed.Zed .sdc all
duti -s dev.zed.Zed .tcl.in all
duti -s dev.zed.Zed .tm all
duti -s dev.zed.Zed .xdc all
duti -s dev.zed.Zed .tcsh all
duti -s dev.zed.Zed .csh all
duti -s dev.zed.Zed .tex all
duti -s dev.zed.Zed .aux all
duti -s dev.zed.Zed .bbx all
duti -s dev.zed.Zed .cbx all
duti -s dev.zed.Zed .cls all
duti -s dev.zed.Zed .dtx all
duti -s dev.zed.Zed .ins all
duti -s dev.zed.Zed .lbx all
duti -s dev.zed.Zed .ltx all
duti -s dev.zed.Zed .mkii all
duti -s dev.zed.Zed .mkiv all
duti -s dev.zed.Zed .mkvi all
duti -s dev.zed.Zed .sty all
duti -s dev.zed.Zed .toc all
duti -s dev.zed.Zed .tea all
duti -s dev.zed.Zed .t all
duti -s dev.zed.Zed .tftpl all
duti -s dev.zed.Zed .texinfo all
duti -s dev.zed.Zed .texi all
duti -s dev.zed.Zed .txi all
duti -s dev.zed.Zed .txt all
duti -s dev.zed.Zed .fr all
duti -s dev.zed.Zed .nb all
duti -s dev.zed.Zed .ncl all
duti -s dev.zed.Zed .no all
duti -s dev.zed.Zed .tm_properties all
duti -s dev.zed.Zed .textile all
duti -s dev.zed.Zed .thrift all
duti -s dev.zed.Zed .toit all
duti -s dev.zed.Zed .t all
duti -s dev.zed.Zed .tu all
duti -s dev.zed.Zed .ttl all
duti -s dev.zed.Zed .twig all
duti -s dev.zed.Zed .tl all
duti -s dev.zed.Zed .ts all
duti -s dev.zed.Zed .cts all
duti -s dev.zed.Zed .mts all
duti -s dev.zed.Zed .typ all
duti -s dev.zed.Zed .upc all
duti -s dev.zed.Zed .anim all
duti -s dev.zed.Zed .asset all
duti -s dev.zed.Zed .mask all
duti -s dev.zed.Zed .mat all
duti -s dev.zed.Zed .meta all
duti -s dev.zed.Zed .prefab all
duti -s dev.zed.Zed .unity all
duti -s dev.zed.Zed .s all
duti -s dev.zed.Zed .ms all
duti -s dev.zed.Zed .uno all
duti -s dev.zed.Zed .uc all
duti -s dev.zed.Zed .ur all
duti -s dev.zed.Zed .urs all
duti -s dev.zed.Zed .v all
duti -s dev.zed.Zed .bas all
duti -s dev.zed.Zed .cls all
duti -s dev.zed.Zed .frm all
duti -s dev.zed.Zed .vba all
duti -s dev.zed.Zed .vbs all
duti -s dev.zed.Zed .vcl all
duti -s dev.zed.Zed .vhdl all
duti -s dev.zed.Zed .vhd all
duti -s dev.zed.Zed .vhf all
duti -s dev.zed.Zed .vhi all
duti -s dev.zed.Zed .vho all
duti -s dev.zed.Zed .vhs all
duti -s dev.zed.Zed .vht all
duti -s dev.zed.Zed .vhw all
duti -s dev.zed.Zed .vala all
duti -s dev.zed.Zed .vapi all
duti -s dev.zed.Zed .vdf all
duti -s dev.zed.Zed .vtl all
duti -s dev.zed.Zed .v all
duti -s dev.zed.Zed .veo all
duti -s dev.zed.Zed .txt all
duti -s dev.zed.Zed .vim all
duti -s dev.zed.Zed .vba all
duti -s dev.zed.Zed .vimrc all
duti -s dev.zed.Zed .vmb all
duti -s dev.zed.Zed .exrc all
duti -s dev.zed.Zed .gvimrc all
duti -s dev.zed.Zed .nvimrc all
duti -s dev.zed.Zed .vimrc all
duti -s dev.zed.Zed .snip all
duti -s dev.zed.Zed .snippet all
duti -s dev.zed.Zed .snippets all
duti -s dev.zed.Zed .vb all
duti -s dev.zed.Zed .vbhtml all
duti -s dev.zed.Zed .bas all
duti -s dev.zed.Zed .cls all
duti -s dev.zed.Zed .ctl all
duti -s dev.zed.Zed .Dsr all
duti -s dev.zed.Zed .frm all
duti -s dev.zed.Zed .volt all
duti -s dev.zed.Zed .vue all
duti -s dev.zed.Zed .vy all
duti -s dev.zed.Zed .wdl all
duti -s dev.zed.Zed .wgsl all
duti -s dev.zed.Zed .mtl all
duti -s dev.zed.Zed .obj all
duti -s dev.zed.Zed .owl all
duti -s dev.zed.Zed .wast all
duti -s dev.zed.Zed .wat all
duti -s dev.zed.Zed .wit all
duti -s dev.zed.Zed .webidl all
duti -s dev.zed.Zed .vtt all
duti -s dev.zed.Zed .wgetrc all
duti -s dev.zed.Zed .whiley all
duti -s dev.zed.Zed .mediawiki all
duti -s dev.zed.Zed .wiki all
duti -s dev.zed.Zed .wikitext all
duti -s dev.zed.Zed .mc all
duti -s dev.zed.Zed .reg all
duti -s dev.zed.Zed .ws all
duti -s dev.zed.Zed .wlk all
duti -s dev.zed.Zed .toc all
duti -s dev.zed.Zed .wren all
duti -s dev.zed.Zed .xbm all
duti -s dev.zed.Zed .xpm all
duti -s dev.zed.Zed .pm all
duti -s dev.zed.Zed .x10 all
duti -s dev.zed.Zed .xc all
duti -s dev.zed.Zed .XCompose all
duti -s dev.zed.Zed .xml all
duti -s dev.zed.Zed .adml all
duti -s dev.zed.Zed .admx all
duti -s dev.zed.Zed .ant all
duti -s dev.zed.Zed .axaml all
duti -s dev.zed.Zed .axml all
duti -s dev.zed.Zed .builds all
duti -s dev.zed.Zed .ccproj all
duti -s dev.zed.Zed .ccxml all
duti -s dev.zed.Zed .clixml all
duti -s dev.zed.Zed .cproject all
duti -s dev.zed.Zed .cscfg all
duti -s dev.zed.Zed .csdef all
duti -s dev.zed.Zed .csl all
duti -s dev.zed.Zed .csproj all
duti -s dev.zed.Zed .ct all
duti -s dev.zed.Zed .depproj all
duti -s dev.zed.Zed .dita all
duti -s dev.zed.Zed .ditamap all
duti -s dev.zed.Zed .ditaval all
duti -s dev.zed.Zed .dll.config all
duti -s dev.zed.Zed .dotsettings all
duti -s dev.zed.Zed .filters all
duti -s dev.zed.Zed .fsproj all
duti -s dev.zed.Zed .fxml all
duti -s dev.zed.Zed .glade all
duti -s dev.zed.Zed .gml all
duti -s dev.zed.Zed .gmx all
duti -s dev.zed.Zed .grxml all
duti -s dev.zed.Zed .gst all
duti -s dev.zed.Zed .hzp all
duti -s dev.zed.Zed .iml all
duti -s dev.zed.Zed .ivy all
duti -s dev.zed.Zed .jelly all
duti -s dev.zed.Zed .jsproj all
duti -s dev.zed.Zed .kml all
duti -s dev.zed.Zed .launch all
duti -s dev.zed.Zed .mdpolicy all
duti -s dev.zed.Zed .mjml all
duti -s dev.zed.Zed .mm all
duti -s dev.zed.Zed .mod all
duti -s dev.zed.Zed .mxml all
duti -s dev.zed.Zed .natvis all
duti -s dev.zed.Zed .ncl all
duti -s dev.zed.Zed .ndproj all
duti -s dev.zed.Zed .nproj all
duti -s dev.zed.Zed .nuspec all
duti -s dev.zed.Zed .odd all
duti -s dev.zed.Zed .osm all
duti -s dev.zed.Zed .pkgproj all
duti -s dev.zed.Zed .pluginspec all
duti -s dev.zed.Zed .proj all
duti -s dev.zed.Zed .props all
duti -s dev.zed.Zed .ps1xml all
duti -s dev.zed.Zed .psc1 all
duti -s dev.zed.Zed .pt all
duti -s dev.zed.Zed .qhelp all
duti -s dev.zed.Zed .rdf all
duti -s dev.zed.Zed .res all
duti -s dev.zed.Zed .resx all
duti -s dev.zed.Zed .rs all
duti -s dev.zed.Zed .rss all
duti -s dev.zed.Zed .sch all
duti -s dev.zed.Zed .scxml all
duti -s dev.zed.Zed .sfproj all
duti -s dev.zed.Zed .shproj all
duti -s dev.zed.Zed .srdf all
duti -s dev.zed.Zed .storyboard all
duti -s dev.zed.Zed .sublime-snippet all
duti -s dev.zed.Zed .sw all
duti -s dev.zed.Zed .targets all
duti -s dev.zed.Zed .tml all
duti -s dev.zed.Zed .ts all
duti -s dev.zed.Zed .tsx all
duti -s dev.zed.Zed .typ all
duti -s dev.zed.Zed .ui all
duti -s dev.zed.Zed .urdf all
duti -s dev.zed.Zed .ux all
duti -s dev.zed.Zed .vbproj all
duti -s dev.zed.Zed .vcxproj all
duti -s dev.zed.Zed .vsixmanifest all
duti -s dev.zed.Zed .vssettings all
duti -s dev.zed.Zed .vstemplate all
duti -s dev.zed.Zed .vxml all
duti -s dev.zed.Zed .wixproj all
duti -s dev.zed.Zed .workflow all
duti -s dev.zed.Zed .wsdl all
duti -s dev.zed.Zed .wsf all
duti -s dev.zed.Zed .wxi all
duti -s dev.zed.Zed .wxl all
duti -s dev.zed.Zed .wxs all
duti -s dev.zed.Zed .x3d all
duti -s dev.zed.Zed .xacro all
duti -s dev.zed.Zed .xaml all
duti -s dev.zed.Zed .xib all
duti -s dev.zed.Zed .xlf all
duti -s dev.zed.Zed .xliff all
duti -s dev.zed.Zed .xmi all
duti -s dev.zed.Zed .xml.dist all
duti -s dev.zed.Zed .xmp all
duti -s dev.zed.Zed .xproj all
duti -s dev.zed.Zed .xsd all
duti -s dev.zed.Zed .xspec all
duti -s dev.zed.Zed .xul all
duti -s dev.zed.Zed .zcml all
duti -s dev.zed.Zed .classpath all
duti -s dev.zed.Zed .cproject all
duti -s dev.zed.Zed .project all
duti -s dev.zed.Zed .plist all
duti -s dev.zed.Zed .stTheme all
duti -s dev.zed.Zed .tmCommand all
duti -s dev.zed.Zed .tmLanguage all
duti -s dev.zed.Zed .tmPreferences all
duti -s dev.zed.Zed .tmSnippet all
duti -s dev.zed.Zed .tmTheme all
duti -s dev.zed.Zed .xsp-config all
duti -s dev.zed.Zed .xsp.metadata all
duti -s dev.zed.Zed .xpl all
duti -s dev.zed.Zed .xproc all
duti -s dev.zed.Zed .xquery all
duti -s dev.zed.Zed .xq all
duti -s dev.zed.Zed .xql all
duti -s dev.zed.Zed .xqm all
duti -s dev.zed.Zed .xqy all
duti -s dev.zed.Zed .xs all
duti -s dev.zed.Zed .xslt all
duti -s dev.zed.Zed .xsl all
duti -s dev.zed.Zed .xojo_code all
duti -s dev.zed.Zed .xojo_menu all
duti -s dev.zed.Zed .xojo_report all
duti -s dev.zed.Zed .xojo_script all
duti -s dev.zed.Zed .xojo_toolbar all
duti -s dev.zed.Zed .xojo_window all
duti -s dev.zed.Zed .xsh all
duti -s dev.zed.Zed .xtend all
duti -s dev.zed.Zed .yml all
duti -s dev.zed.Zed .mir all
duti -s dev.zed.Zed .reek all
duti -s dev.zed.Zed .rviz all
duti -s dev.zed.Zed .sublime-syntax all
duti -s dev.zed.Zed .syntax all
duti -s dev.zed.Zed .yaml all
duti -s dev.zed.Zed .yaml-tmlanguage all
duti -s dev.zed.Zed .yaml.sed all
duti -s dev.zed.Zed .yml.mysql all
duti -s dev.zed.Zed .clang-format all
duti -s dev.zed.Zed .clang-tidy all
duti -s dev.zed.Zed .gemrc all
duti -s dev.zed.Zed .yang all
duti -s dev.zed.Zed .yar all
duti -s dev.zed.Zed .yara all
duti -s dev.zed.Zed .yasnippet all
duti -s dev.zed.Zed .y all
duti -s dev.zed.Zed .yacc all
duti -s dev.zed.Zed .yy all
duti -s dev.zed.Zed .yul all
duti -s dev.zed.Zed .zap all
duti -s dev.zed.Zed .xzap all
duti -s dev.zed.Zed .zil all
duti -s dev.zed.Zed .mud all
duti -s dev.zed.Zed .zeek all
duti -s dev.zed.Zed .bro all
duti -s dev.zed.Zed .zs all
duti -s dev.zed.Zed .zep all
duti -s dev.zed.Zed .zig all
duti -s dev.zed.Zed .zimpl all
duti -s dev.zed.Zed .zmpl all
duti -s dev.zed.Zed .zpl all
duti -s dev.zed.Zed .curlrc all
duti -s dev.zed.Zed .desktop all
duti -s dev.zed.Zed .desktop.in all
duti -s dev.zed.Zed .service all
duti -s dev.zed.Zed .dircolors all
duti -s dev.zed.Zed .dir_colors all
duti -s dev.zed.Zed .dircolors all
duti -s dev.zed.Zed .ec all
duti -s dev.zed.Zed .eh all
duti -s dev.zed.Zed .edn all
duti -s dev.zed.Zed .fish all
duti -s dev.zed.Zed .hoon all
duti -s dev.zed.Zed .jq all
duti -s dev.zed.Zed .kv all
duti -s dev.zed.Zed .mrc all
duti -s dev.zed.Zed .mcfunction all
duti -s dev.zed.Zed .mu all
duti -s dev.zed.Zed .nanorc all
duti -s dev.zed.Zed .nanorc all
duti -s dev.zed.Zed .nc all
duti -s dev.zed.Zed .ooc all
duti -s dev.zed.Zed .q all
duti -s dev.zed.Zed .rst all
duti -s dev.zed.Zed .rest all
duti -s dev.zed.Zed .rest.txt all
duti -s dev.zed.Zed .rst.txt all
duti -s dev.zed.Zed .sed all
duti -s dev.zed.Zed .wisp all
duti -s dev.zed.Zed .prg all
duti -s dev.zed.Zed .ch all
duti -s dev.zed.Zed .prw all
duti -s dev.zed.Zed .css all
duti -s dev.zed.Zed .go all
duti -s dev.zed.Zed .java all
duti -s dev.zed.Zed .js all
duti -s dev.zed.Zed .cfg all
duti -s dev.zed.Zed .json all
duti -s dev.zed.Zed .md all
duti -s dev.zed.Zed .py all
duti -s dev.zed.Zed .rb all
duti -s dev.zed.Zed .rs all
duti -s dev.zed.Zed .sh all
duti -s dev.zed.Zed .swift all
duti -s dev.zed.Zed .txt all
duti -s dev.zed.Zed .conf all
duti -s dev.zed.Zed .properties all
duti -s dev.zed.Zed .yaml all
duti -s dev.zed.Zed .yml all
duti -s dev.zed.Zed .xml all
duti -s dev.zed.Zed .nomad all
duti -s dev.zed.Zed .Jenkinsfile all
duti -s dev.zed.Zed Jenkinsfile all
echo 'duti associations done'
